name: ediars Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install redis fakeredis pytest pathvalidate python-dotenv
      - name: Run Pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pytest test_db_service.py test_ediars.py